trigger: none

# Run PR validation on all branches
pr:
  branches:
    include:
    - 'master'



pool:
  vmImage: ubuntu-latest
  demands:
  - msbuild
  - visualstudio
  - vstest


variables:
  #Pipeline
  poolName: 'ubuntu-latest'
  #Build
  solution: '**/*.sln'
  testConfiguration: 'Debug'
  buildPlatform: 'Any CPU'
stages:
  - stage: Test 
    displayName: Unit Test
    jobs:
      - job: Test
        displayName: Unit Test
        steps:
          - task: NuGetToolInstaller@1
            displayName: 'Nuget Installer'
          - task: NuGetCommand@2
            inputs:
              restoreSolution: '$(solution)'
          - task: DotNetCoreCLI@2
            displayName: 'Build Test'
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration $(testConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: 'Unit Test'
            inputs:
              command: 'test'
              projects: 'test/*/*.csproj's